<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace></RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DefineConstants>DEBUG,TRACE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="DevExpress.Document.Processor" Version="24.2.3" />
	  <PackageReference Include="DevExpress.Drawing.Skia" Version="24.2.3" />
  </ItemGroup>

</Project>
